spring:
  profiles:
    # 默认激活 dev 环境
    active: dev

jwt:
  # 签发人
  issuer: wuyonghua
  # 密钥
  secret: RiDIPm7UNgRtcK9u9rgrjIdRfzMEncQJTuJZo1c01yrnyi/N0WdfyOq4KdcFXiSl5c8ikBEMgUbULdRpibP5SQ==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer
